# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc "Otto8 CLI"
  homepage "https://github.com/otto8-ai/otto8"
  version "0.1.0-rc1"

  on_macos do
    on_intel do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.1.0-rc1/otto8_v0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "bb73fe24dd019e1b8aa2e624ae57320849c7c88e0d150ccd27485b718b70c9d3"

      def install
        bin.install "otto8"
      end
    end
    on_arm do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.1.0-rc1/otto8_v0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "25f235670bb78f89bae68fd14a8bb1b629d81693049946fe1d4e0e229f52ad8c"

      def install
        bin.install "otto8"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.1.0-rc1/otto8_v0.1.0-rc1_linux_amd64.tar.gz"
        sha256 "4bf4b3d9bf168ece6cf558e32f19748c6c86f4594e7ba7e225b313aa2a4c8dd1"

        def install
          bin.install "otto8"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.1.0-rc1/otto8_v0.1.0-rc1_linux_arm64.tar.gz"
        sha256 "df79880a53d3951488986f7989c122f8b73b45c29d03ffb1684a9b1859a6ae8a"

        def install
          bin.install "otto8"
        end
      end
    end
  end
end
