# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otto8 < Formula
  desc "Otto8 CLI"
  homepage "https://github.com/otto8-ai/otto8"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0/otto8_v0.2.0_darwin_amd64.tar.gz"
      sha256 "124af12531a7472d2dea257de9d5d3a480e98bf14e88681de582cf8691041855"

      def install
        bin.install "otto8"
      end
    end
    on_arm do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0/otto8_v0.2.0_darwin_arm64.tar.gz"
      sha256 "d476267415b0b0d904b41f93c2890eb3151ee8ad81d8ce56cbca5549387eb82d"

      def install
        bin.install "otto8"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0/otto8_v0.2.0_linux_amd64.tar.gz"
        sha256 "8c3ea77bf0f5a944ca09d6c879b67cedc1a97f58ccf36d46f176330072e917f3"

        def install
          bin.install "otto8"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0/otto8_v0.2.0_linux_arm64.tar.gz"
        sha256 "b9ea581b396817a299ffa56d7641df083984db83e5d19df520ef6fae38430bf4"

        def install
          bin.install "otto8"
        end
      end
    end
  end
end
