# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Otto8 < Formula
  desc "Otto8 CLI"
  homepage "https://github.com/otto8-ai/otto8"
  version "0.2.0-rc1"

  on_macos do
    on_intel do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0-rc1/otto8_v0.2.0-rc1_darwin_amd64.tar.gz"
      sha256 "01ecdcb25a861d1366b400f98ec0100274df34cd62c896fdf5347652d58c3342"

      def install
        bin.install "otto8"
      end
    end
    on_arm do
      url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0-rc1/otto8_v0.2.0-rc1_darwin_arm64.tar.gz"
      sha256 "361751c515e0b9304e9d3ae30d4f457926f696eeb83d7e0d7a36f751aaf9dc53"

      def install
        bin.install "otto8"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0-rc1/otto8_v0.2.0-rc1_linux_amd64.tar.gz"
        sha256 "a20c2d3cf6f2e7253e6d6149c5820ff1710f993e249617a87e53185100794187"

        def install
          bin.install "otto8"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/otto8-ai/otto8/releases/download/v0.2.0-rc1/otto8_v0.2.0-rc1_linux_arm64.tar.gz"
        sha256 "dd68c01a4fe2491d13e3a3f857416cda13def47f64097824d71229bf544a4c2a"

        def install
          bin.install "otto8"
        end
      end
    end
  end
end
